@localBaseUrl = http://localhost:4000
@azureBaseUrl = https://pre-reg-spike-api-gncmescydpgebuhj.canadacentral-01.azurewebsites.net

# Switch this between {{localBaseUrl}} and {{azureBaseUrl}}
@baseUrl = {{localBaseUrl}}

@apiKey = 37339cb4-4761-4e5f-91c0-16a5687f3ae6
@tournamentId = 7

### Create registration (requires API key)
POST {{baseUrl}}/api/tournaments/{{tournamentId}}/registrations
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "email": "michelle.schroder@example.com",
  "participant": {
    "firstName": "Michelle",
    "lastName": "Schroder",
    "age": 49,
    "genderId": 2,
    "beltRankId": 7,
    "notes": "From Test harness", 
    "dojoId": 12,
    "otherDojoName": null
  },
  "events": ["kumite"]
}

### Create second participant with same email (should reuse user)
POST {{baseUrl}}/api/tournaments/{{tournamentId}}/registrations
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "email": "michelle.schroder@example.com",
  "participant": {
    "firstName": "John",
    "lastName": "Schroder",
    "age": 12,
    "genderId": 1,
    "beltRankId": 5,
    "notes": "Second child registration", 
    "dojoId": 12
  },
  "events": ["kata", "kumite"]
}

### Ping the server
GET {{baseUrl}}/ping

### Get all registrations for the tournament
GET {{baseUrl}}/api/tournaments/{{tournamentId}}/participants
X-API-Key: {{apiKey}}

