@baseUrl = http://localhost:4000
@tournamentId = 10
POST {{baseUrl}}/api/tournaments/{{tournamentId}}/registrations
Content-Type: application/json

{
  "userId": 2,
  "participant": {
    "firstName": "Avery",
    "lastName": "Jones",
    "age": 6,
    "genderId": 1,
    "beltRankId": 1,
    "notes": "Testing registration"
  },
  "events": ["kumite"]
}

### Get all registrations for the tournament
GET {{baseUrl}}/api/tournaments/{{tournamentId}}/participants
X-API-Key: 37339cb4-4761-4e5f-91c0-16a5687f3ae6
