@localBaseUrl = http://localhost:4000
@azureBaseUrl = https://pre-reg-spike-api-gncmescydpgebuhj.canadacentral-01.azurewebsites.net

# Switch this between {{localBaseUrl}} and {{azureBaseUrl}}
@baseUrl = {{localBaseUrl}}

@apiKey = 37339cb4-4761-4e5f-91c0-16a5687f3ae6
@tournamentId = 7

### Create registration (requires API key)
POST {{baseUrl}}/api/tournaments/{{tournamentId}}/registrations
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "userId": 2,
  "participant": {
    "firstName": "Michelle",
    "lastName": "Schroder",
    "age": 49,
    "genderId": 2,
    "beltRankId": 7,
    "notes": "From Test harness", 
    "dojoId": 12,
    
    "UUID": "123e4567-e89b-12d3-a456-426614174000"
  },
  "events": ["kumite"]
}

### Ping the server
GET {{baseUrl}}/ping

### Get all registrations for the tournament
GET {{baseUrl}}/api/tournaments/{{tournamentId}}/participants
X-API-Key: {{apiKey}}

