/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as TournamentParticipantIndexRouteImport } from './routes/tournament/participant/index'
import { Route as TournamentOrganizerCreateRouteImport } from './routes/tournament/organizer/create'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as TournamentParticipantRegisterIdRouteImport } from './routes/tournament/participant/register.$id'
import { Route as TournamentOrganizerEventsTournamentIdRouteImport } from './routes/tournament/organizer/events.$tournamentId'
import { Route as TournamentOrganizerCreatedIdRouteImport } from './routes/tournament/organizer/created.$id'
import { Route as TournamentApiTournmentEventsRouteImport } from './routes/tournament/api.tournment.events'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentParticipantIndexRoute =
  TournamentParticipantIndexRouteImport.update({
    id: '/tournament/participant/',
    path: '/tournament/participant/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentOrganizerCreateRoute =
  TournamentOrganizerCreateRouteImport.update({
    id: '/tournament/organizer/create',
    path: '/tournament/organizer/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentParticipantRegisterIdRoute =
  TournamentParticipantRegisterIdRouteImport.update({
    id: '/tournament/participant/register/$id',
    path: '/tournament/participant/register/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentOrganizerEventsTournamentIdRoute =
  TournamentOrganizerEventsTournamentIdRouteImport.update({
    id: '/tournament/organizer/events/$tournamentId',
    path: '/tournament/organizer/events/$tournamentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentOrganizerCreatedIdRoute =
  TournamentOrganizerCreatedIdRouteImport.update({
    id: '/tournament/organizer/created/$id',
    path: '/tournament/organizer/created/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentApiTournmentEventsRoute =
  TournamentApiTournmentEventsRouteImport.update({
    id: '/tournament/api/tournment/events',
    path: '/tournament/api/tournment/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/tournament/organizer/create': typeof TournamentOrganizerCreateRoute
  '/tournament/participant': typeof TournamentParticipantIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/tournament/api/tournment/events': typeof TournamentApiTournmentEventsRoute
  '/tournament/organizer/created/$id': typeof TournamentOrganizerCreatedIdRoute
  '/tournament/organizer/events/$tournamentId': typeof TournamentOrganizerEventsTournamentIdRoute
  '/tournament/participant/register/$id': typeof TournamentParticipantRegisterIdRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/tournament/organizer/create': typeof TournamentOrganizerCreateRoute
  '/tournament/participant': typeof TournamentParticipantIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/tournament/api/tournment/events': typeof TournamentApiTournmentEventsRoute
  '/tournament/organizer/created/$id': typeof TournamentOrganizerCreatedIdRoute
  '/tournament/organizer/events/$tournamentId': typeof TournamentOrganizerEventsTournamentIdRoute
  '/tournament/participant/register/$id': typeof TournamentParticipantRegisterIdRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/tournament/organizer/create': typeof TournamentOrganizerCreateRoute
  '/tournament/participant/': typeof TournamentParticipantIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/tournament/api/tournment/events': typeof TournamentApiTournmentEventsRoute
  '/tournament/organizer/created/$id': typeof TournamentOrganizerCreatedIdRoute
  '/tournament/organizer/events/$tournamentId': typeof TournamentOrganizerEventsTournamentIdRoute
  '/tournament/participant/register/$id': typeof TournamentParticipantRegisterIdRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/neon'
    | '/demo/table'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/tournament/organizer/create'
    | '/tournament/participant'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/tournament/api/tournment/events'
    | '/tournament/organizer/created/$id'
    | '/tournament/organizer/events/$tournamentId'
    | '/tournament/participant/register/$id'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/neon'
    | '/demo/table'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/tournament/organizer/create'
    | '/tournament/participant'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/tournament/api/tournment/events'
    | '/tournament/organizer/created/$id'
    | '/tournament/organizer/events/$tournamentId'
    | '/tournament/participant/register/$id'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/demo/neon'
    | '/demo/table'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/tournament/organizer/create'
    | '/tournament/participant/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/tournament/api/tournment/events'
    | '/tournament/organizer/created/$id'
    | '/tournament/organizer/events/$tournamentId'
    | '/tournament/participant/register/$id'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  TournamentOrganizerCreateRoute: typeof TournamentOrganizerCreateRoute
  TournamentParticipantIndexRoute: typeof TournamentParticipantIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  TournamentApiTournmentEventsRoute: typeof TournamentApiTournmentEventsRoute
  TournamentOrganizerCreatedIdRoute: typeof TournamentOrganizerCreatedIdRoute
  TournamentOrganizerEventsTournamentIdRoute: typeof TournamentOrganizerEventsTournamentIdRoute
  TournamentParticipantRegisterIdRoute: typeof TournamentParticipantRegisterIdRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/participant/': {
      id: '/tournament/participant/'
      path: '/tournament/participant'
      fullPath: '/tournament/participant'
      preLoaderRoute: typeof TournamentParticipantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/organizer/create': {
      id: '/tournament/organizer/create'
      path: '/tournament/organizer/create'
      fullPath: '/tournament/organizer/create'
      preLoaderRoute: typeof TournamentOrganizerCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/participant/register/$id': {
      id: '/tournament/participant/register/$id'
      path: '/tournament/participant/register/$id'
      fullPath: '/tournament/participant/register/$id'
      preLoaderRoute: typeof TournamentParticipantRegisterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/organizer/events/$tournamentId': {
      id: '/tournament/organizer/events/$tournamentId'
      path: '/tournament/organizer/events/$tournamentId'
      fullPath: '/tournament/organizer/events/$tournamentId'
      preLoaderRoute: typeof TournamentOrganizerEventsTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/organizer/created/$id': {
      id: '/tournament/organizer/created/$id'
      path: '/tournament/organizer/created/$id'
      fullPath: '/tournament/organizer/created/$id'
      preLoaderRoute: typeof TournamentOrganizerCreatedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/api/tournment/events': {
      id: '/tournament/api/tournment/events'
      path: '/tournament/api/tournment/events'
      fullPath: '/tournament/api/tournment/events'
      preLoaderRoute: typeof TournamentApiTournmentEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoTableRoute: DemoTableRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  TournamentOrganizerCreateRoute: TournamentOrganizerCreateRoute,
  TournamentParticipantIndexRoute: TournamentParticipantIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  TournamentApiTournmentEventsRoute: TournamentApiTournmentEventsRoute,
  TournamentOrganizerCreatedIdRoute: TournamentOrganizerCreatedIdRoute,
  TournamentOrganizerEventsTournamentIdRoute:
    TournamentOrganizerEventsTournamentIdRoute,
  TournamentParticipantRegisterIdRoute: TournamentParticipantRegisterIdRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
