/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as TournamentParticipantIndexRouteImport } from './routes/tournament/participant/index'
import { Route as TournamentOrganizerIndexRouteImport } from './routes/tournament/organizer/index'
import { Route as TournamentOrganizerRegistrationSummaryRouteImport } from './routes/tournament/organizer/registration-summary'
import { Route as TournamentOrganizerCreateRouteImport } from './routes/tournament/organizer/create'
import { Route as TournamentOrganizerManageRegistrantsIdRouteImport } from './routes/tournament/organizer/manage-registrants.$id'
import { Route as TournamentOrganizerManageDivisionsIdRouteImport } from './routes/tournament/organizer/manage-divisions.$id'
import { Route as TournamentOrganizerEventsTournamentIdRouteImport } from './routes/tournament/organizer/events.$tournamentId'
import { Route as TournamentOrganizerCreatedIdRouteImport } from './routes/tournament/organizer/created.$id'
import { Route as TournamentApiTournmentEventsRouteImport } from './routes/tournament/api.tournment.events'
import { Route as TournamentParticipantRegisterIdIndexRouteImport } from './routes/tournament/participant/register/$id/index'
import { Route as TournamentParticipantRegisterIdWaiverAgreementRouteImport } from './routes/tournament/participant/register/$id/waiver-agreement'
import { Route as TournamentParticipantRegisterIdSubmitEntryRouteImport } from './routes/tournament/participant/register/$id/submit-entry'
import { Route as TournamentParticipantRegisterIdSelectEventsRouteImport } from './routes/tournament/participant/register/$id/select-events'
import { Route as TournamentParticipantRegisterIdCreateParticipantRouteImport } from './routes/tournament/participant/register/$id/create-participant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentParticipantIndexRoute =
  TournamentParticipantIndexRouteImport.update({
    id: '/tournament/participant/',
    path: '/tournament/participant/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentOrganizerIndexRoute =
  TournamentOrganizerIndexRouteImport.update({
    id: '/tournament/organizer/',
    path: '/tournament/organizer/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentOrganizerRegistrationSummaryRoute =
  TournamentOrganizerRegistrationSummaryRouteImport.update({
    id: '/tournament/organizer/registration-summary',
    path: '/tournament/organizer/registration-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentOrganizerCreateRoute =
  TournamentOrganizerCreateRouteImport.update({
    id: '/tournament/organizer/create',
    path: '/tournament/organizer/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentOrganizerManageRegistrantsIdRoute =
  TournamentOrganizerManageRegistrantsIdRouteImport.update({
    id: '/tournament/organizer/manage-registrants/$id',
    path: '/tournament/organizer/manage-registrants/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentOrganizerManageDivisionsIdRoute =
  TournamentOrganizerManageDivisionsIdRouteImport.update({
    id: '/tournament/organizer/manage-divisions/$id',
    path: '/tournament/organizer/manage-divisions/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentOrganizerEventsTournamentIdRoute =
  TournamentOrganizerEventsTournamentIdRouteImport.update({
    id: '/tournament/organizer/events/$tournamentId',
    path: '/tournament/organizer/events/$tournamentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentOrganizerCreatedIdRoute =
  TournamentOrganizerCreatedIdRouteImport.update({
    id: '/tournament/organizer/created/$id',
    path: '/tournament/organizer/created/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentApiTournmentEventsRoute =
  TournamentApiTournmentEventsRouteImport.update({
    id: '/tournament/api/tournment/events',
    path: '/tournament/api/tournment/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentParticipantRegisterIdIndexRoute =
  TournamentParticipantRegisterIdIndexRouteImport.update({
    id: '/tournament/participant/register/$id/',
    path: '/tournament/participant/register/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentParticipantRegisterIdWaiverAgreementRoute =
  TournamentParticipantRegisterIdWaiverAgreementRouteImport.update({
    id: '/tournament/participant/register/$id/waiver-agreement',
    path: '/tournament/participant/register/$id/waiver-agreement',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentParticipantRegisterIdSubmitEntryRoute =
  TournamentParticipantRegisterIdSubmitEntryRouteImport.update({
    id: '/tournament/participant/register/$id/submit-entry',
    path: '/tournament/participant/register/$id/submit-entry',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentParticipantRegisterIdSelectEventsRoute =
  TournamentParticipantRegisterIdSelectEventsRouteImport.update({
    id: '/tournament/participant/register/$id/select-events',
    path: '/tournament/participant/register/$id/select-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentParticipantRegisterIdCreateParticipantRoute =
  TournamentParticipantRegisterIdCreateParticipantRouteImport.update({
    id: '/tournament/participant/register/$id/create-participant',
    path: '/tournament/participant/register/$id/create-participant',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/table': typeof DemoTableRoute
  '/tournament/organizer/create': typeof TournamentOrganizerCreateRoute
  '/tournament/organizer/registration-summary': typeof TournamentOrganizerRegistrationSummaryRoute
  '/tournament/organizer': typeof TournamentOrganizerIndexRoute
  '/tournament/participant': typeof TournamentParticipantIndexRoute
  '/tournament/api/tournment/events': typeof TournamentApiTournmentEventsRoute
  '/tournament/organizer/created/$id': typeof TournamentOrganizerCreatedIdRoute
  '/tournament/organizer/events/$tournamentId': typeof TournamentOrganizerEventsTournamentIdRoute
  '/tournament/organizer/manage-divisions/$id': typeof TournamentOrganizerManageDivisionsIdRoute
  '/tournament/organizer/manage-registrants/$id': typeof TournamentOrganizerManageRegistrantsIdRoute
  '/tournament/participant/register/$id/create-participant': typeof TournamentParticipantRegisterIdCreateParticipantRoute
  '/tournament/participant/register/$id/select-events': typeof TournamentParticipantRegisterIdSelectEventsRoute
  '/tournament/participant/register/$id/submit-entry': typeof TournamentParticipantRegisterIdSubmitEntryRoute
  '/tournament/participant/register/$id/waiver-agreement': typeof TournamentParticipantRegisterIdWaiverAgreementRoute
  '/tournament/participant/register/$id': typeof TournamentParticipantRegisterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/table': typeof DemoTableRoute
  '/tournament/organizer/create': typeof TournamentOrganizerCreateRoute
  '/tournament/organizer/registration-summary': typeof TournamentOrganizerRegistrationSummaryRoute
  '/tournament/organizer': typeof TournamentOrganizerIndexRoute
  '/tournament/participant': typeof TournamentParticipantIndexRoute
  '/tournament/api/tournment/events': typeof TournamentApiTournmentEventsRoute
  '/tournament/organizer/created/$id': typeof TournamentOrganizerCreatedIdRoute
  '/tournament/organizer/events/$tournamentId': typeof TournamentOrganizerEventsTournamentIdRoute
  '/tournament/organizer/manage-divisions/$id': typeof TournamentOrganizerManageDivisionsIdRoute
  '/tournament/organizer/manage-registrants/$id': typeof TournamentOrganizerManageRegistrantsIdRoute
  '/tournament/participant/register/$id/create-participant': typeof TournamentParticipantRegisterIdCreateParticipantRoute
  '/tournament/participant/register/$id/select-events': typeof TournamentParticipantRegisterIdSelectEventsRoute
  '/tournament/participant/register/$id/submit-entry': typeof TournamentParticipantRegisterIdSubmitEntryRoute
  '/tournament/participant/register/$id/waiver-agreement': typeof TournamentParticipantRegisterIdWaiverAgreementRoute
  '/tournament/participant/register/$id': typeof TournamentParticipantRegisterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/table': typeof DemoTableRoute
  '/tournament/organizer/create': typeof TournamentOrganizerCreateRoute
  '/tournament/organizer/registration-summary': typeof TournamentOrganizerRegistrationSummaryRoute
  '/tournament/organizer/': typeof TournamentOrganizerIndexRoute
  '/tournament/participant/': typeof TournamentParticipantIndexRoute
  '/tournament/api/tournment/events': typeof TournamentApiTournmentEventsRoute
  '/tournament/organizer/created/$id': typeof TournamentOrganizerCreatedIdRoute
  '/tournament/organizer/events/$tournamentId': typeof TournamentOrganizerEventsTournamentIdRoute
  '/tournament/organizer/manage-divisions/$id': typeof TournamentOrganizerManageDivisionsIdRoute
  '/tournament/organizer/manage-registrants/$id': typeof TournamentOrganizerManageRegistrantsIdRoute
  '/tournament/participant/register/$id/create-participant': typeof TournamentParticipantRegisterIdCreateParticipantRoute
  '/tournament/participant/register/$id/select-events': typeof TournamentParticipantRegisterIdSelectEventsRoute
  '/tournament/participant/register/$id/submit-entry': typeof TournamentParticipantRegisterIdSubmitEntryRoute
  '/tournament/participant/register/$id/waiver-agreement': typeof TournamentParticipantRegisterIdWaiverAgreementRoute
  '/tournament/participant/register/$id/': typeof TournamentParticipantRegisterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/table'
    | '/tournament/organizer/create'
    | '/tournament/organizer/registration-summary'
    | '/tournament/organizer'
    | '/tournament/participant'
    | '/tournament/api/tournment/events'
    | '/tournament/organizer/created/$id'
    | '/tournament/organizer/events/$tournamentId'
    | '/tournament/organizer/manage-divisions/$id'
    | '/tournament/organizer/manage-registrants/$id'
    | '/tournament/participant/register/$id/create-participant'
    | '/tournament/participant/register/$id/select-events'
    | '/tournament/participant/register/$id/submit-entry'
    | '/tournament/participant/register/$id/waiver-agreement'
    | '/tournament/participant/register/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/table'
    | '/tournament/organizer/create'
    | '/tournament/organizer/registration-summary'
    | '/tournament/organizer'
    | '/tournament/participant'
    | '/tournament/api/tournment/events'
    | '/tournament/organizer/created/$id'
    | '/tournament/organizer/events/$tournamentId'
    | '/tournament/organizer/manage-divisions/$id'
    | '/tournament/organizer/manage-registrants/$id'
    | '/tournament/participant/register/$id/create-participant'
    | '/tournament/participant/register/$id/select-events'
    | '/tournament/participant/register/$id/submit-entry'
    | '/tournament/participant/register/$id/waiver-agreement'
    | '/tournament/participant/register/$id'
  id:
    | '__root__'
    | '/'
    | '/demo/table'
    | '/tournament/organizer/create'
    | '/tournament/organizer/registration-summary'
    | '/tournament/organizer/'
    | '/tournament/participant/'
    | '/tournament/api/tournment/events'
    | '/tournament/organizer/created/$id'
    | '/tournament/organizer/events/$tournamentId'
    | '/tournament/organizer/manage-divisions/$id'
    | '/tournament/organizer/manage-registrants/$id'
    | '/tournament/participant/register/$id/create-participant'
    | '/tournament/participant/register/$id/select-events'
    | '/tournament/participant/register/$id/submit-entry'
    | '/tournament/participant/register/$id/waiver-agreement'
    | '/tournament/participant/register/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTableRoute: typeof DemoTableRoute
  TournamentOrganizerCreateRoute: typeof TournamentOrganizerCreateRoute
  TournamentOrganizerRegistrationSummaryRoute: typeof TournamentOrganizerRegistrationSummaryRoute
  TournamentOrganizerIndexRoute: typeof TournamentOrganizerIndexRoute
  TournamentParticipantIndexRoute: typeof TournamentParticipantIndexRoute
  TournamentApiTournmentEventsRoute: typeof TournamentApiTournmentEventsRoute
  TournamentOrganizerCreatedIdRoute: typeof TournamentOrganizerCreatedIdRoute
  TournamentOrganizerEventsTournamentIdRoute: typeof TournamentOrganizerEventsTournamentIdRoute
  TournamentOrganizerManageDivisionsIdRoute: typeof TournamentOrganizerManageDivisionsIdRoute
  TournamentOrganizerManageRegistrantsIdRoute: typeof TournamentOrganizerManageRegistrantsIdRoute
  TournamentParticipantRegisterIdCreateParticipantRoute: typeof TournamentParticipantRegisterIdCreateParticipantRoute
  TournamentParticipantRegisterIdSelectEventsRoute: typeof TournamentParticipantRegisterIdSelectEventsRoute
  TournamentParticipantRegisterIdSubmitEntryRoute: typeof TournamentParticipantRegisterIdSubmitEntryRoute
  TournamentParticipantRegisterIdWaiverAgreementRoute: typeof TournamentParticipantRegisterIdWaiverAgreementRoute
  TournamentParticipantRegisterIdIndexRoute: typeof TournamentParticipantRegisterIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/participant/': {
      id: '/tournament/participant/'
      path: '/tournament/participant'
      fullPath: '/tournament/participant'
      preLoaderRoute: typeof TournamentParticipantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/organizer/': {
      id: '/tournament/organizer/'
      path: '/tournament/organizer'
      fullPath: '/tournament/organizer'
      preLoaderRoute: typeof TournamentOrganizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/organizer/registration-summary': {
      id: '/tournament/organizer/registration-summary'
      path: '/tournament/organizer/registration-summary'
      fullPath: '/tournament/organizer/registration-summary'
      preLoaderRoute: typeof TournamentOrganizerRegistrationSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/organizer/create': {
      id: '/tournament/organizer/create'
      path: '/tournament/organizer/create'
      fullPath: '/tournament/organizer/create'
      preLoaderRoute: typeof TournamentOrganizerCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/organizer/manage-registrants/$id': {
      id: '/tournament/organizer/manage-registrants/$id'
      path: '/tournament/organizer/manage-registrants/$id'
      fullPath: '/tournament/organizer/manage-registrants/$id'
      preLoaderRoute: typeof TournamentOrganizerManageRegistrantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/organizer/manage-divisions/$id': {
      id: '/tournament/organizer/manage-divisions/$id'
      path: '/tournament/organizer/manage-divisions/$id'
      fullPath: '/tournament/organizer/manage-divisions/$id'
      preLoaderRoute: typeof TournamentOrganizerManageDivisionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/organizer/events/$tournamentId': {
      id: '/tournament/organizer/events/$tournamentId'
      path: '/tournament/organizer/events/$tournamentId'
      fullPath: '/tournament/organizer/events/$tournamentId'
      preLoaderRoute: typeof TournamentOrganizerEventsTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/organizer/created/$id': {
      id: '/tournament/organizer/created/$id'
      path: '/tournament/organizer/created/$id'
      fullPath: '/tournament/organizer/created/$id'
      preLoaderRoute: typeof TournamentOrganizerCreatedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/api/tournment/events': {
      id: '/tournament/api/tournment/events'
      path: '/tournament/api/tournment/events'
      fullPath: '/tournament/api/tournment/events'
      preLoaderRoute: typeof TournamentApiTournmentEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/participant/register/$id/': {
      id: '/tournament/participant/register/$id/'
      path: '/tournament/participant/register/$id'
      fullPath: '/tournament/participant/register/$id'
      preLoaderRoute: typeof TournamentParticipantRegisterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/participant/register/$id/waiver-agreement': {
      id: '/tournament/participant/register/$id/waiver-agreement'
      path: '/tournament/participant/register/$id/waiver-agreement'
      fullPath: '/tournament/participant/register/$id/waiver-agreement'
      preLoaderRoute: typeof TournamentParticipantRegisterIdWaiverAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/participant/register/$id/submit-entry': {
      id: '/tournament/participant/register/$id/submit-entry'
      path: '/tournament/participant/register/$id/submit-entry'
      fullPath: '/tournament/participant/register/$id/submit-entry'
      preLoaderRoute: typeof TournamentParticipantRegisterIdSubmitEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/participant/register/$id/select-events': {
      id: '/tournament/participant/register/$id/select-events'
      path: '/tournament/participant/register/$id/select-events'
      fullPath: '/tournament/participant/register/$id/select-events'
      preLoaderRoute: typeof TournamentParticipantRegisterIdSelectEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/participant/register/$id/create-participant': {
      id: '/tournament/participant/register/$id/create-participant'
      path: '/tournament/participant/register/$id/create-participant'
      fullPath: '/tournament/participant/register/$id/create-participant'
      preLoaderRoute: typeof TournamentParticipantRegisterIdCreateParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTableRoute: DemoTableRoute,
  TournamentOrganizerCreateRoute: TournamentOrganizerCreateRoute,
  TournamentOrganizerRegistrationSummaryRoute:
    TournamentOrganizerRegistrationSummaryRoute,
  TournamentOrganizerIndexRoute: TournamentOrganizerIndexRoute,
  TournamentParticipantIndexRoute: TournamentParticipantIndexRoute,
  TournamentApiTournmentEventsRoute: TournamentApiTournmentEventsRoute,
  TournamentOrganizerCreatedIdRoute: TournamentOrganizerCreatedIdRoute,
  TournamentOrganizerEventsTournamentIdRoute:
    TournamentOrganizerEventsTournamentIdRoute,
  TournamentOrganizerManageDivisionsIdRoute:
    TournamentOrganizerManageDivisionsIdRoute,
  TournamentOrganizerManageRegistrantsIdRoute:
    TournamentOrganizerManageRegistrantsIdRoute,
  TournamentParticipantRegisterIdCreateParticipantRoute:
    TournamentParticipantRegisterIdCreateParticipantRoute,
  TournamentParticipantRegisterIdSelectEventsRoute:
    TournamentParticipantRegisterIdSelectEventsRoute,
  TournamentParticipantRegisterIdSubmitEntryRoute:
    TournamentParticipantRegisterIdSubmitEntryRoute,
  TournamentParticipantRegisterIdWaiverAgreementRoute:
    TournamentParticipantRegisterIdWaiverAgreementRoute,
  TournamentParticipantRegisterIdIndexRoute:
    TournamentParticipantRegisterIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
